In [25]:
import numpy as np
import pandas as pd
import geopandas as gpd
import itertools
from ast import literal_eval

In [118]:
df = pd.read_csv("data/tbi_full.csv")
df

,wave,person_id,trip_id,travel_date,travel_dow,depart_time,arrive_time,duration,distance,vehicle_trips,...,senior,student,unemployed,parent,person_type,gender_cleaned,o_car_terminal_time,d_car_terminal_time,car_duration_seconds_adj,bike_duration_seconds_adj
0,1,1811206201,[1811206201001],2018-12-06,Thursday,12:30:00,13:00:00,23.0,16.443340,1.0,...,False,False,False,True,working adult with kids,Female,1.0,1.0,1335.6,14862.5
1,1,1811206201,[1811206201002],2018-12-06,Thursday,22:00:00,22:30:00,22.0,16.462600,1.0,...,False,False,False,True,working adult with kids,Female,1.0,1.0,1337.4,14862.5
2,1,1811206203,[1811206203001],2018-12-06,Thursday,05:45:00,06:45:00,14.0,9.543020,0.0,...,False,True,True,True,non-working adult with kids,Male,1.0,1.0,1065.6,6754.2
3,1,1811206203,[1811206203002],2018-12-06,Thursday,14:00:00,15:00:00,14.0,9.546120,0.0,...,False,True,True,True,non-working adult with kids,Male,1.0,1.0,1126.5,6754.2
4,1,1811206204,[1811206204001],2018-12-06,Thursday,10:45:00,11:15:00,12.0,8.328860,0.0,...,False,True,True,True,non-working adult with kids,Male,1.0,1.0,943.5,6490.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
454176,2,2200279003,[2200279003003],2022-01-27,Thursday,23:13:00,23:34:00,21.0,1.694825,1.0,...,False,False,False,True,working adult with kids,Male,1.0,3.0,670.7,1678.2
454177,2,2200279101,[2200279101001],2022-01-26,Wednesday,14:06:00,14:26:00,20.0,4.468702,1.0,...,False,False,False,False,working adult without kids,Female,1.0,1.0,754.0,3478.2
454178,2,2200279101,[2200279101002],2022-01-26,Wednesday,23:03:00,23:29:00,26.0,2.566255,1.0,...,False,False,False,False,working adult without kids,Female,1.0,1.0,741.4,3478.2
454179,2,2200279102,[2200279102001],2022-01-26,Wednesday,13:50:00,14:15:00,25.0,1.760551,0.0,...,False,False,False,False,working adult without kids,Male,1.0,1.0,532.4,2372.2
454180,2,2200279102,[2200279102002],2022-01-26,Wednesday,23:00:00,23:20:00,20.0,5.274406,0.0,...,False,False,False,False,working adult without kids,Male,1.0,1.0,505.5,2372.2

In [119]:
drop_cols = ['bike_trip_id', 'd_lat', 'home_lon', 'student', 'o_lon', 'gender', 'd_lon', 'job_type', 'walk_trip_id', 'home_lat', 'child', 'senior', 'travel_dow', 'student_status', 'temperature_max', 'o_lat', 'transit_trip_id', 'parent', 'age', 'unemployed', 'num_kids', 'temperature_min', 'walk_weight', 'bike_weight']
df_anonymous = df.drop(drop_cols, axis=1)

In [120]:
df_anonymous["person_id"] = pd.factorize(df["person_id"])[0]

In [121]:
trips = list(itertools.chain(*df["trip_id"].apply(lambda x: literal_eval(str(x))).values))
temp = pd.factorize(trips)
trip_conversion = dict(zip(temp[1], temp[0]))
trip_conversion

{1811206201001: 0,
 1811206201002: 1,
 1811206203001: 2,
 1811206203002: 3,
 1811206204001: 4,
 1811206204002: 5,
 1811206205001: 6,
 1811206205002: 7,
 1811424401001: 8,
 1811424401002: 9,
 1811424401003: 10,
 1811424401004: 11,
 1811424401005: 12,
 1811424401006: 13,
 1811424401007: 14,
 1811424401008: 15,
 1811424401009: 16,
 1811424401010: 17,
 1811424401011: 18,
 1811424401012: 19,
 1811424401013: 20,
 1811424401014: 21,
 1811424402001: 22,
 1811424402002: 23,
 1811424402003: 24,
 1811424402004: 25,
 1811424402005: 26,
 1811424402006: 27,
 1811424402007: 28,
 1811424402008: 29,
 1811424402009: 30,
 1811424402010: 31,
 1811424402011: 32,
 1811424402012: 33,
 1811424402013: 34,
 1811424402014: 35,
 1811424402015: 36,
 1811424402016: 37,
 1811424402017: 38,
 1811424402018: 39,
 1811424402019: 40,
 1811424402020: 41,
 1811424402021: 42,
 1811424402022: 43,
 1811424402023: 44,
 1811424402024: 45,
 1811424402025: 46,
 1811424402026: 47,
 1811424402027: 48,
 1811424402028: 49,
 1811424402029: 50,
 1811424402030: 51,
 1811424402031: 52,
 1811424402032: 53,
 1811424402033: 54,
 1811424402034: 55,
 1811424402035: 56,
 1811424402036: 57,
 1811424402037: 58,
 1811424402038: 59,
 1811424402039: 60,
 1811424402040: 61,
 1811424402041: 62,
 1811424402042: 63,
 1811424402043: 64,
 1811424402044: 65,
 1811424402045: 66,
 1811424403001: 67,
 1811424403002: 68,
 1811424403003: 69,
 1811424403004: 70,
 1811424403005: 71,
 1811424403006: 72,
 1811424403007: 73,
 1811424403008: 74,
 1811424403009: 75,
 1811424403010: 76,
 1811424403011: 77,
 1811424403012: 78,
 1811424403013: 79,
 1811424404001: 80,
 1811424404002: 81,
 1811424404003: 82,
 1811424404004: 83,
 1811424404005: 84,
 1811424404006: 85,
 1811424404007: 86,
 1811424404008: 87,
 1811424404009: 88,
 1811424404010: 89,
 1811424404011: 90,
 1811424404012: 91,
 1811424405001: 92,
 1811424405002: 93,
 1811424405003: 94,
 1811424405004: 95,
 1811424405005: 96,
 1811424405006: 97,
 1811424405007: 98,
 1811424406001: 99,
 1811424406002: 100,
 1811424406003: 101,
 1811424406004: 102,
 1811424406005: 103,
 1811424406006: 104,
 1811430401001: 105,
 1811430401002: 106,
 1811430401003: 107,
 1811430401004: 108,
 1811430401005: 109,
 1811430401006: 110,
 1811430401007: 111,
 1811430401008: 112,
 1811430401009: 113,
 1811430401010: 114,
 1811430401011: 115,
 1811430401012: 116,
 1811430401013: 117,
 1811430401014: 118,
 1811430401015: 119,
 1811430401016: 120,
 1811430401017: 121,
 1811430401018: 122,
 1811430401019: 123,
 1811430401020: 124,
 1811430401021: 125,
 1811430401022: 126,
 1811430401023: 127,
 1811430401024: 128,
 1811430401025: 129,
 1811430401026: 130,
 1811430401028: 131,
 1811430401029: 132,
 1811430401030: 133,
 1811430401031: 134,
 1811430401032: 135,
 1811453601001: 136,
 1811453601002: 137,
 1811453601003: 138,
 1811453601004: 139,
 1811453601005: 140,
 1811453601006: 141,
 1811453601007: 142,
 1811453601008: 143,
 1811453601009: 144,
 1811453601010: 145,
 1811453601011: 146,
 1811453601012: 147,
 1811453601013: 148,
 1811453601014: 149,
 1811453601015: 150,
 1811453601016: 151,
 1811453601017: 152,
 1811453601018: 153,
 1811453601019: 154,
 1811453601020: 155,
 1811453601021: 156,
 1811453601022: 157,
 1811453602001: 158,
 1811453602002: 159,
 1811453602003: 160,
 1811453602004: 161,
 1811453602005: 162,
 1811469501001: 163,
 1811469501002: 164,
 1811469501003: 165,
 1811469501004: 166,
 1811469501005: 167,
 1811469501006: 168,
 1811469501007: 169,
 1811469501008: 170,
 1811469501009: 171,
 1811469501010: 172,
 1811469501011: 173,
 1811469501012: 174,
 1811469501013: 175,
 1811469501014: 176,
 1811469501015: 177,
 1811469501016: 178,
 1811469502001: 179,
 1811469502002: 180,
 1811469502003: 181,
 1811469502004: 182,
 1811469502005: 183,
 1811469502006: 184,
 1811469502007: 185,
 1811469502008: 186,
 1811469502009: 187,
 1811469502010: 188,
 1811469502011: 189,
 1811469503001: 190,
 1811469503002: 191,
 1811469503003: 192,
 1811469503004: 193,
 1811469503005: 194,
 1811469503006: 195,
 1811469503007: 196,
 1811469503008: 197,
 1811469503009: 198,
 1811469503010: 199,
 1811469503011: 200,
 1811469503012: 201,
 1811469504001: 202,
 1811469504002: 203,
 1811469504003: 204,
 1811469504004: 205,
 1811469504005: 206,
 1811469504006: 207,
 1811469504007: 208,
 1811469504008: 209,
 1811469504009: 210,
 1811469504010: 211,
 1811469504011: 212,
 1811469504012: 213,
 1811541101001: 214,
 1811541101002: 215,
 1811541101003: 216,
 1811541101004: 217,
 1811541101005: 218,
 1811541101006: 219,
 1811541101007: 220,
 1811541101008: 221,
 1811541101009: 222,
 1811541101010: 223,
 1811541101011: 224,
 1811541101012: 225,
 1811541101013: 226,
 1811541101014: 227,
 1811541101015: 228,
 1811541101016: 229,
 1811541101017: 230,
 1811541101018: 231,
 1811541101019: 232,
 1811541101020: 233,
 1811541101021: 234,
 1811541101022: 235,
 1811541101023: 236,
 1811541101024: 237,
 1811541101025: 238,
 1811541101026: 239,
 1811541101027: 240,
 1811541101028: 241,
 1811541101029: 242,
 1811541101030: 243,
 1811541101031: 244,
 1811541101032: 245,
 1811541101033: 246,
 1811541101034: 247,
 1811541101035: 248,
 1811541101037: 249,
 1811541101038: 250,
 1811541101039: 251,
 1811541101040: 252,
 1811541101041: 253,
 1811541101042: 254,
 1811541101043: 255,
 1811541101044: 256,
 1811541101045: 257,
 1811541101046: 258,
 1811541102001: 259,
 1811541102002: 260,
 1811541102003: 261,
 1811541102004: 262,
 1811541102005: 263,
 1811541102006: 264,
 1811541102007: 265,
 1811541102008: 266,
 1811541102009: 267,
 1811541102010: 268,
 1811541102011: 269,
 1811541102012: 270,
 1811541102014: 271,
 1811541102015: 272,
 1811541102016: 273,
 1811541102017: 274,
 1811541102018: 275,
 1811541102019: 276,
 1811541102020: 277,
 1811541102021: 278,
 1811541102022: 279,
 1811541102023: 280,
 1811541102024: 281,
 1811541102025: 282,
 1811541102026: 283,
 1811541102027: 284,
 1811541102028: 285,
 1811541102029: 286,
 1811541102030: 287,
 1811541102031: 288,
 1811541102032: 289,
 1811541102033: 290,
 1811541102034: 291,
 1811541102035: 292,
 1811541102036: 293,
 1811541102037: 294,
 1811541102038: 295,
 1811541102039: 296,
 1811541102040: 297,
 1811541102041: 298,
 1811541102042: 299,
 1811541102044: 300,
 1811541102045: 301,
 1811541102046: 302,
 1811582101001: 303,
 1811582101002: 304,
 1811582101003: 305,
 1811635201001: 306,
 1811635201002: 307,
 1811645301001: 308,
 1811645301002: 309,
 1811645301003: 310,
 1811645301004: 311,
 1811645301005: 312,
 1811645301006: 313,
 1811645301007: 314,
 1811645301008: 315,
 1811645301009: 316,
 1811645301010: 317,
 1811645301011: 318,
 1811645301012: 319,
 1811645301013: 320,
 1811645301014: 321,
 1811645301015: 322,
 1811645301016: 323,
 1811645301017: 324,
 1811645301018: 325,
 1811645301019: 326,
 1811645301020: 327,
 1811645301021: 328,
 1811645301022: 329,
 1811645301023: 330,
 1811645301024: 331,
 1811645301025: 332,
 1811645302001: 333,
 1811645302002: 334,
 1811645302003: 335,
 1811645302004: 336,
 1811645302005: 337,
 1811645302006: 338,
 1811645302007: 339,
 1811645302008: 340,
 1811645302009: 341,
 1811645302010: 342,
 1811645302011: 343,
 1811645302012: 344,
 1811645302013: 345,
 1811645302014: 346,
 1811645302015: 347,
 1811645302016: 348,
 1811645302017: 349,
 1811645302018: 350,
 1811645302019: 351,
 1811645302020: 352,
 1811645302021: 353,
 1811645302022: 354,
 1811645302023: 355,
 1811645302024: 356,
 1811645302025: 357,
 1811645302026: 358,
 1811645302027: 359,
 1811645302028: 360,
 1811645302029: 361,
 1811645302030: 362,
 1811676601001: 363,
 1811676601002: 364,
 1811676601003: 365,
 1811676601004: 366,
 1811676601005: 367,
 1811676601006: 368,
 1811676601007: 369,
 1811676601008: 370,
 1811676601009: 371,
 1811676601010: 372,
 1811676601011: 373,
 1811676601012: 374,
 1811676601013: 375,
 1811676601014: 376,
 1811676601015: 377,
 1811676601016: 378,
 1811676601017: 379,
 1811676601018: 380,
 1811676601019: 381,
 1811676601020: 382,
 1811676601021: 383,
 1811676601022: 384,
 1811676601023: 385,
 1811676601024: 386,
 1811676601025: 387,
 1811676601026: 388,
 1811676601027: 389,
 1811676601028: 390,
 1811676601029: 391,
 1811676601030: 392,
 1811676601031: 393,
 1811676601032: 394,
 1811710001001: 395,
 1811710001002: 396,
 1811710001003: 397,
 1811710001004: 398,
 1811710001005: 399,
 1811710001006: 400,
 1811710001007: 401,
 1811710001008: 402,
 1811710001009: 403,
 1811710001010: 404,
 1811710001011: 405,
 1811710001012: 406,
 1811710001013: 407,
 1811710001014: 408,
 1811710001015: 409,
 1811710001016: 410,
 1811710001017: 411,
 1811710001018: 412,
 1811710001019: 413,
 1811710001020: 414,
 1811710001021: 415,
 1811710001022: 416,
 1811710001023: 417,
 1811710001024: 418,
 1811710001025: 419,
 1811710001026: 420,
 1811710001027: 421,
 1811710001028: 422,
 1811710001029: 423,
 1811711101001: 424,
 1811711101002: 425,
 1811711101003: 426,
 1811711101004: 427,
 1811711101005: 428,
 1811711101006: 429,
 1811711101007: 430,
 1811711101008: 431,
 1811711101009: 432,
 1811711101010: 433,
 1811711101011: 434,
 1811711101012: 435,
 1811711101013: 436,
 1811711101014: 437,
 1811711101015: 438,
 1811711101016: 439,
 1811711101017: 440,
 1811711101018: 441,
 1811711101019: 442,
 1811711101020: 443,
 1811711101021: 444,
 1811711101022: 445,
 1811711101023: 446,
 1811711101024: 447,
 1811711101025: 448,
 1811711101026: 449,
 1811711101027: 450,
 1811711101029: 451,
 1811711101030: 452,
 1811711101031: 453,
 1811711101032: 454,
 1811711101035: 455,
 1811711101036: 456,
 1811711101037: 457,
 1811711101038: 458,
 1811711101039: 459,
 1811711101040: 460,
 1811711101041: 461,
 1811711101042: 462,
 1811711102001: 463,
 1811711102002: 464,
 1811711102004: 465,
 1811711102005: 466,
 1811711102006: 467,
 1811711102007: 468,
 1811711102008: 469,
 1811711102009: 470,
 1811711102010: 471,
 1811711102011: 472,
 1811711102012: 473,
 1811711102013: 474,
 1811711102014: 475,
 1811711102015: 476,
 1811711102016: 477,
 1811711102017: 478,
 1811711102018: 479,
 1811711102019: 480,
 1811711102020: 481,
 1811711102021: 482,
 1811711102022: 483,
 1811711102023: 484,
 1811711102024: 485,
 1811711102025: 486,
 1811711102026: 487,
 1811711102027: 488,
 1811711102028: 489,
 1811711102029: 490,
 1811711102030: 491,
 1811711102031: 492,
 1811711102032: 493,
 1811711102033: 494,
 1811711102034: 495,
 1811711102035: 496,
 1811711102036: 497,
 1811711102037: 498,
 1811711102038: 499,
 1811711102039: 500,
 1811711102040: 501,
 1811711102041: 502,
 1811711102042: 503,
 1811711102043: 504,
 1811711102044: 505,
 1811711102045: 506,
 1811711102046: 507,
 1811711102047: 508,
 1811711102048: 509,
 1811711102049: 510,
 1811711102050: 511,
 1811711102051: 512,
 1811711102052: 513,
 1811711102053: 514,
 1811711102054: 515,
 1811711102055: 516,
 1811711102056: 517,
 1811711102057: 518,
 1811711102058: 519,
 1811711102059: 520,
 1811711102060: 521,
 1811711102061: 522,
 1811711102062: 523,
 1811711103001: 524,
 1811711103002: 525,
 1811711103003: 526,
 1811711103004: 527,
 1811711103005: 528,
 1811711103006: 529,
 1811711103007: 530,
 1811711103008: 531,
 1811711103009: 532,
 1811711103010: 533,
 1811711103011: 534,
 1811711103012: 535,
 1811711103013: 536,
 1811711103014: 537,
 1811711103015: 538,
 1811711103016: 539,
 1811711103017: 540,
 1811711103018: 541,
 1811711103019: 542,
 1811711103020: 543,
 1811711103021: 544,
 1811711103022: 545,
 1811711103023: 546,
 1811711103024: 547,
 1811711103025: 548,
 1811711103026: 549,
 1811711103027: 550,
 1811711103028: 551,
 1811711103029: 552,
 1811711103030: 553,
 1811711103031: 554,
 1811711103032: 555,
 1811711103033: 556,
 1811711103034: 557,
 1811711103035: 558,
 1811711103036: 559,
 1811711103037: 560,
 1811711103038: 561,
 1811711103039: 562,
 1811711103040: 563,
 1811711104001: 564,
 1811711104002: 565,
 1811711104003: 566,
 1811711104004: 567,
 1811711104005: 568,
 1811711104006: 569,
 1811711104007: 570,
 1811711104008: 571,
 1811711104009: 572,
 1811711104010: 573,
 1811711104011: 574,
 1811711104012: 575,
 1811711104013: 576,
 1811711104014: 577,
 1811711104015: 578,
 1811711104016: 579,
 1811711104017: 580,
 1811711104018: 581,
 1811711104019: 582,
 1811711104020: 583,
 1811711104021: 584,
 1811711104022: 585,
 1811711104023: 586,
 1811711104024: 587,
 1811711104025: 588,
 1811711104026: 589,
 1811711104027: 590,
 1811711104028: 591,
 1811711104029: 592,
 1811711104030: 593,
 1811711104031: 594,
 1811711104032: 595,
 1811711104033: 596,
 1811711104034: 597,
 1811711104035: 598,
 1811711104036: 599,
 1811711104037: 600,
 1811711104038: 601,
 1811711104039: 602,
 1811711104040: 603,
 1811711104041: 604,
 1811711104042: 605,
 1811711104043: 606,
 1811711104044: 607,
 1811711104045: 608,
 1811711104046: 609,
 1811711104047: 610,
 1811711701001: 611,
 1811711701002: 612,
 1811711701003: 613,
 1811711701004: 614,
 1811711701005: 615,
 1811711701006: 616,
 1811711701007: 617,
 1811711701008: 618,
 1811711701009: 619,
 1811711701010: 620,
 1811711701011: 621,
 1811711701012: 622,
 1811711701013: 623,
 1811711701014: 624,
 1811711701015: 625,
 1811711701016: 626,
 1811711701017: 627,
 1811711701018: 628,
 1811711701019: 629,
 1811711701020: 630,
 1811711701021: 631,
 1811711701022: 632,
 1811711701023: 633,
 1811711701024: 634,
 1811711701025: 635,
 1811711701026: 636,
 1811711701027: 637,
 1811711701028: 638,
 1811711701029: 639,
 1811711701030: 640,
 1811711701031: 641,
 1811711701032: 642,
 1811711701033: 643,
 1811711701034: 644,
 1811711701035: 645,
 1811711701036: 646,
 1811711701037: 647,
 1811711701038: 648,
 1811721901001: 649,
 1811721901002: 650,
 1811721901003: 651,
 1811721901004: 652,
 1811721901005: 653,
 1811721901006: 654,
 1811721901007: 655,
 1811721901008: 656,
 1811721901009: 657,
 1811721901010: 658,
 1811721901012: 659,
 1811721901013: 660,
 1811892301001: 661,
 1811892301002: 662,
 1811892301003: 663,
 1811892301004: 664,
 1811892301005: 665,
 1811892301006: 666,
 1811892301007: 667,
 1811892301008: 668,
 1811892301009: 669,
 1811892301010: 670,
 1811892301011: 671,
 1811892302001: 672,
 1811892302002: 673,
 1811892302003: 674,
 1811892302004: 675,
 1811892302005: 676,
 1811892302006: 677,
 1811892302007: 678,
 1811892302008: 679,
 1811892302009: 680,
 1811903401001: 681,
 1811903401002: 682,
 1811903401003: 683,
 1811903401004: 684,
 1811903401005: 685,
 1811903401006: 686,
 1811903401007: 687,
 1811903401008: 688,
 1811903401009: 689,
 1811903401010: 690,
 1811903401011: 691,
 1811903401012: 692,
 1811903401013: 693,
 1811903401014: 694,
 1811903401015: 695,
 1811903401016: 696,
 1811903401017: 697,
 1811903401018: 698,
 1811903401019: 699,
 1811903401020: 700,
 1811903401021: 701,
 1811934201001: 702,
 1811934201002: 703,
 1811934201003: 704,
 1811934201004: 705,
 1811934201005: 706,
 1811934201006: 707,
 1811934201007: 708,
 1811934201008: 709,
 1811934201010: 710,
 1811934201011: 711,
 1811934201012: 712,
 1811934201013: 713,
 1811934201014: 714,
 1811934201015: 715,
 1811934201016: 716,
 1811934201017: 717,
 1811934201018: 718,
 1811934201019: 719,
 1811934201020: 720,
 1811934201021: 721,
 1811934201022: 722,
 1811934201023: 723,
 1811934201024: 724,
 1811934201025: 725,
 1811934201026: 726,
 1811934201027: 727,
 1811934202003: 728,
 1811934202004: 729,
 1811934202005: 730,
 1811934202006: 731,
 1811934202009: 732,
 1811934202011: 733,
 1811934202013: 734,
 1811934202014: 735,
 1811934202017: 736,
 1811934202018: 737,
 1811934202019: 738,
 1811934202022: 739,
 1811934202023: 740,
 1811934202024: 741,
 1811934202025: 742,
 1811934202028: 743,
 1811934202029: 744,
 1811934202030: 745,
 1811934202031: 746,
 1811934202032: 747,
 1811934202033: 748,
 1811934202034: 749,
 1811934202035: 750,
 1811934202036: 751,
 1811934202037: 752,
 1811934202038: 753,
 1811934202039: 754,
 1811934202040: 755,
 1811934202041: 756,
 1811934202042: 757,
 1811934202043: 758,
 1811934202044: 759,
 1811934202045: 760,
 1811934202046: 761,
 1811934202047: 762,
 1811934202048: 763,
 1811934203001: 764,
 1811934203002: 765,
 1811934203003: 766,
 1811934203004: 767,
 1811934203006: 768,
 1811934203007: 769,
 1811934203009: 770,
 1811934203010: 771,
 1811934203011: 772,
 1811934203013: 773,
 1811934203014: 774,
 1811934203015: 775,
 1811934203016: 776,
 1811934203017: 777,
 1811934203018: 778,
 1811934203019: 779,
 1811934203020: 780,
 1811934203021: 781,
 1811998201001: 782,
 1811998201002: 783,
 1811998201003: 784,
 1811998201004: 785,
 1811998201005: 786,
 1811998201006: 787,
 1811998201007: 788,
 1811998201008: 789,
 1811998201009: 790,
 1811998201010: 791,
 1811998201011: 792,
 1811998201012: 793,
 1811998201013: 794,
 1811998201014: 795,
 1811998201015: 796,
 1811998201016: 797,
 1811998201017: 798,
 1811998201018: 799,
 1811998201019: 800,
 1811998201020: 801,
 1811998201021: 802,
 1811998201022: 803,
 1811998201023: 804,
 1811998201024: 805,
 1811998201025: 806,
 1811998201026: 807,
 1811998201027: 808,
 1811998201028: 809,
 1811998201029: 810,
 1811998201030: 811,
 1811998201031: 812,
 1811998201032: 813,
 1811998201033: 814,
 1811998201034: 815,
 1811998201035: 816,
 1811998201036: 817,
 1811998201037: 818,
 1811998201038: 819,
 1811998201039: 820,
 1811998201040: 821,
 1811998201041: 822,
 1811998201042: 823,
 1811998201043: 824,
 1811998201044: 825,
 1811998201045: 826,
 1811998202001: 827,
 1811998202002: 828,
 1811998202003: 829,
 1811998202004: 830,
 1811998202005: 831,
 1811998202006: 832,
 1811998202007: 833,
 1811998202008: 834,
 1811998202009: 835,
 1811998202010: 836,
 1811998202011: 837,
 1811998202012: 838,
 1811998202013: 839,
 1811998202014: 840,
 1811998202015: 841,
 1811998202016: 842,
 1811998203001: 843,
 1811998203002: 844,
 1811998203003: 845,
 1811998203004: 846,
 1811998203005: 847,
 1811998203006: 848,
 1811998203007: 849,
 1811998203008: 850,
 1811998203009: 851,
 1811998203010: 852,
 1811998203011: 853,
 1811998203012: 854,
 1811998203013: 855,
 1811998203014: 856,
 1811998203015: 857,
 1811998203016: 858,
 1811998203017: 859,
 1811998203018: 860,
 1811998203019: 861,
 1811998203020: 862,
 1811998203021: 863,
 1811998203022: 864,
 1811998203023: 865,
 1811998203024: 866,
 1811998203025: 867,
 1811998203026: 868,
 1811998204001: 869,
 1811998204002: 870,
 1811998204003: 871,
 1811998204004: 872,
 1811998204005: 873,
 1811998204006: 874,
 1811998204007: 875,
 1811998204008: 876,
 1811998204009: 877,
 1811998204010: 878,
 1811998204011: 879,
 1811998204012: 880,
 1811998204013: 881,
 1811998204014: 882,
 1811998204015: 883,
 1811998204016: 884,
 1811998204017: 885,
 1811998204018: 886,
 1811998204019: 887,
 1811998204020: 888,
 1811998204021: 889,
 1811998204022: 890,
 1811998204023: 891,
 1811998204024: 892,
 1811998204025: 893,
 1811998204026: 894,
 1811998204027: 895,
 1811998204028: 896,
 1812042001001: 897,
 1812042001002: 898,
 1812051101001: 899,
 1812051101002: 900,
 1812051101003: 901,
 1812051101004: 902,
 1812051101005: 903,
 1812051101006: 904,
 1812051101007: 905,
 1812051101010: 906,
 1812051101011: 907,
 1812051101012: 908,
 1812051101013: 909,
 1812051101014: 910,
 1812051101015: 911,
 1812051101016: 912,
 1812051101017: 913,
 1812051101018: 914,
 1812051101019: 915,
 1812051101021: 916,
 1812051101022: 917,
 1812051101024: 918,
 1812051101025: 919,
 1812051101026: 920,
 1812051101027: 921,
 1812051101031: 922,
 1812051101033: 923,
 1812051101034: 924,
 1812051101035: 925,
 1812051101036: 926,
 1812051101037: 927,
 1812051101038: 928,
 1812051102001: 929,
 1812051102002: 930,
 1812051102003: 931,
 1812051102004: 932,
 1812051102005: 933,
 1812051102006: 934,
 1812051102007: 935,
 1812051102008: 936,
 1812051102009: 937,
 1812051102010: 938,
 1812051102011: 939,
 1812051102012: 940,
 1812051102013: 941,
 1812051102014: 942,
 1812051102015: 943,
 1812051102016: 944,
 1812051102017: 945,
 1812051102018: 946,
 1812051102019: 947,
 1812051102020: 948,
 1812051102021: 949,
 1812051102022: 950,
 1812051102023: 951,
 1812051102024: 952,
 1812051102025: 953,
 1812051102026: 954,
 1812051102027: 955,
 1812051102028: 956,

In [122]:
def map_trip_ids(x: list) -> list:
    res = list(map(lambda ele: trip_conversion[ele], x))
    return res

df_anonymous["trip_id"] = df["trip_id"].apply(lambda x: literal_eval(x)).apply(lambda x: map_trip_ids(x))

In [123]:
df_anonymous.dtypes

wave                                  int64
person_id                             int64
trip_id                              object
travel_date                          object
depart_time                          object
arrive_time                          object
duration                            float64
distance                            float64
vehicle_trips                       float64
vmt                                 float64
mode                                 object
o_purpose_category                   object
d_purpose_category                   object
income_detailed                      object
temperature                         float64
precipitation                       float64
snowfall                            float64
snow_depth                          float64
car_duration_seconds                float64
car_distance_meters                 float64
walk_duration_seconds               float64
walk_distance_meters                float64
bike_duration_seconds               float64
bike_distance_meters                float64
bike_distance_meters_1              float64
bike_distance_meters_2              float64
bike_distance_meters_3              float64
bike_distance_meters_4              float64
transit_duration                    float64
transit_access_length               float64
transit_num_transfers               float64
transit_non_transit_duration        float64
transit_length                      float64
est_observed_transit_access_dist    float64
transfers                             int64
community                            object
purpose_cleaned                      object
person_type                          object
gender_cleaned                       object
o_car_terminal_time                 float64
d_car_terminal_time                 float64
car_duration_seconds_adj            float64
bike_duration_seconds_adj           float64
dtype: object

In [137]:
df_anonymous["wave"] = df["wave"].astype(np.int8)
df_anonymous["person_id"] = df["wave"].astype(np.int32)
df_anonymous["duration"] = df["duration"].round().astype(np.int16)
df_anonymous["distance"] = df["distance"].round(1).astype(np.float32)
df_anonymous["vehicle_trips"] = df["vehicle_trips"].astype(np.float32)
df_anonymous["vmt"] = df["vmt"].astype(np.float32)
df_anonymous["temperature"] = df["temperature"].astype(np.float32)
df_anonymous["precipitation"] = df["precipitation"].astype(np.float32)
df_anonymous["snowfall"] = df["snowfall"].astype(np.float32)
df_anonymous["car_duration_seconds"] = df["car_duration_seconds"].round().astype(np.int16)
df_anonymous["car_distance_meters"] = df["car_distance_meters"].round().astype(np.int32)
df_anonymous["walk_duration_seconds"] = df["walk_duration_seconds"].round().astype(np.int32)
df_anonymous["walk_distance_meters"] = df["walk_distance_meters"].round().astype(np.int32)
df_anonymous["bike_duration_seconds"] = df["bike_duration_seconds"].round().astype(np.int32)
df_anonymous["bike_distance_meters"] = df["bike_distance_meters"].round().astype(np.int32)
df_anonymous["bike_distance_meters_1"] = df["bike_distance_meters_1"].round().astype(np.int32)
df_anonymous["bike_distance_meters_2"] = df["bike_distance_meters_2"].round().astype(np.int32)
df_anonymous["bike_distance_meters_3"] = df["bike_distance_meters_3"].round().astype(np.int32)
df_anonymous["bike_distance_meters_4"] = df["bike_distance_meters_4"].round().astype(np.int32)
df_anonymous["transit_duration"] = df["transit_duration"].round().astype(np.int16)
df_anonymous["transit_access_length"] = df["transit_access_length"].round().astype(np.int16)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [140]:
df["car_duration_seconds"].isna().sum()

1

In [136]:
(df_anonymous["transit_num_transfers"]).max()

2.0

In [110]:
1.5 % 1

0.5

In [115]:
temp = pd.read_parquet("data/temp.parquet")

In [116]:
temp

,wave,person_id,trip_id,travel_date,depart_time,arrive_time,duration,distance,vehicle_trips,vmt,...,est_observed_transit_access_dist,transfers,community,purpose_cleaned,person_type,gender_cleaned,o_car_terminal_time,d_car_terminal_time,car_duration_seconds_adj,bike_duration_seconds_adj
0,1,0,0,2018-12-06,12:30:00,13:00:00,23.0,16.443340,1.0,16.443340,...,0.0,0,80,Work,working adult with kids,Female,1.0,1.0,1335.6,14862.5
1,1,0,1,2018-12-06,22:00:00,22:30:00,22.0,16.462600,1.0,16.462600,...,0.0,0,80,Home,working adult with kids,Female,1.0,1.0,1337.4,14862.5
2,1,1,2,2018-12-06,05:45:00,06:45:00,14.0,9.543020,0.0,0.000000,...,0.0,0,80,School,non-working adult with kids,Male,1.0,1.0,1065.6,6754.2
3,1,1,3,2018-12-06,14:00:00,15:00:00,14.0,9.546120,0.0,0.000000,...,0.0,0,80,Home,non-working adult with kids,Male,1.0,1.0,1126.5,6754.2
4,1,2,4,2018-12-06,10:45:00,11:15:00,12.0,8.328860,0.0,0.000000,...,0.0,0,80,School,non-working adult with kids,Male,1.0,1.0,943.5,6490.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
454176,2,27079,454176,2022-01-27,23:13:00,23:34:00,21.0,1.694825,1.0,1.694825,...,0.0,0,192,Home,working adult with kids,Male,1.0,3.0,670.7,1678.2
454177,2,27080,454177,2022-01-26,14:06:00,14:26:00,20.0,4.468702,1.0,4.468702,...,0.0,0,141,Work,working adult without kids,Female,1.0,1.0,754.0,3478.2
454178,2,27080,454178,2022-01-26,23:03:00,23:29:00,26.0,2.566255,1.0,2.566255,...,0.0,0,141,Home,working adult without kids,Female,1.0,1.0,741.4,3478.2
454179,2,27081,454179,2022-01-26,13:50:00,14:15:00,25.0,1.760551,0.0,0.000000,...,0.0,0,141,Work,working adult without kids,Male,1.0,1.0,532.4,2372.2
454180,2,27081,454180,2022-01-26,23:00:00,23:20:00,20.0,5.274406,0.0,0.000000,...,0.0,0,141,Home,working adult without kids,Male,1.0,1.0,505.5,2372.2

In [117]:
temp.columns

Index(['wave', 'person_id', 'trip_id', 'travel_date', 'depart_time',
       'arrive_time', 'duration', 'distance', 'vehicle_trips', 'vmt', 'mode',
       'o_purpose_category', 'd_purpose_category', 'income_detailed',
       'temperature', 'precipitation', 'snowfall', 'snow_depth',
       'car_duration_seconds', 'car_distance_meters', 'walk_duration_seconds',
       'walk_distance_meters', 'walk_weight', 'bike_duration_seconds',
       'bike_distance_meters', 'bike_weight', 'bike_distance_meters_1',
       'bike_distance_meters_2', 'bike_distance_meters_3',
       'bike_distance_meters_4', 'transit_duration', 'transit_access_length',
       'transit_num_transfers', 'transit_non_transit_duration',
       'transit_length', 'est_observed_transit_access_dist', 'transfers',
       'community', 'purpose_cleaned', 'person_type', 'gender_cleaned',
       'o_car_terminal_time', 'd_car_terminal_time',
       'car_duration_seconds_adj', 'bike_duration_seconds_adj'],
      dtype='object')